---
# tasks file for dns
- name: Deploy named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0640'
    validate: named-checkconf %s
  notify: Restart named
