---
#Delete old host keys
- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob: "/etc/ssh/ssh_host_*_key"

#Generate new host keys
- name: Generate RSA host key
  command: ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
  args:
    creates: /etc/ssh/ssh_host_rsa_key

- name: Generate ECDSA host key
  command: ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
  args:
    creates: /etc/ssh/ssh_host_ecdsa_key

- name: Generate ED25519 host key
  command: ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
  args:
    creates: /etc/ssh/ssh_host_ed25519_key
  notify: Restart ssh Service

- name: Set new hostname
  ansible.builtin.hostname:
    name: "{{ lab_hostname }}"

- name: Change host
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^(.+)(lab-deb-gold)$'
    replace: '\1{{ lab_hostname }}'

- name: Replace ip
  ansible.builtin.replace:
    path: /etc/network/interfaces
    regexp: '^(.+)address 192\.168\.23\.\d{1,3}\/24$'
    replace: '\1address {{ lab_ip_address }}'
  notify: Restart Network Service
