---
- name: Build kube cluster
  hosts: kube,master,dns
  remote_user: sean
  become: yes
  become_method: sudo
  roles:
    - role: update
  tasks:
  - name: Print a message
    ansible.builtin.debug:
      msg: "this task runs after the example role"
